### ISSUE TITLE
`leetcode show` gives exceptions

### ISSUE THREAD

**Issue by ravioactive** [skygragon/leetcode-cli#104]
### Problem Summary
Running `leetcode show` gives exceptions:
```
17:34 $ lce show
/usr/local/lib/node_modules/leetcode-cli/lib/plugins/lintcode.js:193
    queue.run(LANGS, doTask, function(e) {
          ^

TypeError: queue.run is not a function
    at Request._callback (/usr/local/lib/node_modules/leetcode-cli/lib/plugins/lintcode.js:193:11)
    at Request.self.callback (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
```

### How to reproduce

Running `leetcode show` command.

### Environment

- leetcode-cli version: 2.5.1

- OS version: Mac OSX High Sierra 10.13.4 (17E202)
- Node version: 8.9.4
- Npm version: 6.1.0

**Comment by skygragon** [comment]
This issue was moved to skygragon/leetcode-cli-plugins#15
