### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by riveridea** [skygragon/leetcode-cli#132]
### Problem Summary
Run any leetcodecli command leads to:
leetcode user -l
undefined:1

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.cache.get (/home/changczh/.nvm/versions/node/v10.13.0/lib/node_modules/leetcode-cli/lib/cache.js:17:15)
    at Function.Plugin.init (/home/changczh/.nvm/versions/node/v10.13.0/lib/node_modules/leetcode-cli/lib/plugin.js:131:22)
    at initPlugins (/home/changczh/.nvm/versions/node/v10.13.0/lib/node_modules/leetcode-cli/lib/cli.js:56:14)
    at Object.cli.run (/home/changczh/.nvm/versions/node/v10.13.0/lib/node_modules/leetcode-cli/lib/cli.js:93:3)
    at Object.<anonymous> (/home/changczh/.nvm/versions/node/v10.13.0/lib/node_modules/leetcode-cli/bin/leetcode:3:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)

### How to reproduce
run leetcode user -l
or       leetcode
or       leetcode --version 

### Environment
+ leetcode-cli@2.5.3
updated 208 packages in 69.544s

- OS version: Linux 
- Node version: v10.13.0
- Npm version: 6.4.1

**Comment by riveridea** [comment]
The issue also exists in 2.5.2

**Comment by riveridea** [comment]
the issue is also found with node -v 8.12.0

**Comment by riveridea** [comment]
Any guy who met the same issue?

**Comment by riveridea** [comment]
problem solved:
cd ~/.lc
rm -rf *
vi plugin.json
add {} 
then reinstall leetcode cli and plugins
node -v 
v10.13.0
npm -v 
6.4.1
leetcode version 
2.5.3

**Comment by skygragon** [comment]
@riveridea sounds related to #130 ?
