### ISSUE TITLE
Cannot even run leetcode-cli :Error

### ISSUE THREAD

**Issue by ketankr9** [skygragon/leetcode-cli#135]
Error
```
$$$ ./leetcode-cli -h
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.cache.get (/snapshot/leetcode-cli/lib/cache.js:16:15)
    at Function.Plugin.init (/snapshot/leetcode-cli/lib/plugin.js:86:23)
    at initPlugins (/snapshot/leetcode-cli/lib/cli.js:62:14)
    at Object.cli.run (/snapshot/leetcode-cli/lib/cli.js:100:3)
    at Object.<anonymous> (/snapshot/leetcode-cli/bin/leetcode:3:23)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
```
### Problem Summary

At first it was working good. Then I opened the terminal typed ```leetcode list```, took too long to give any output, closed the terminal. From then leetcode-cli is giving the above error.
### Environment

- leetcode-cli version: leetcode-cli.node10.linux.x64.tar.gz

- OS version: Ubuntu 16.04.5
- Node version:
- Npm version:

**Comment by ketankr9** [comment]
Related to #132, solved using
```
cd ~/.lc
rm -rf *
```
