### ISSUE TITLE
ERROR:leetcode.auth:Network error: url:

### ISSUE THREAD

**Issue by echo-xiao** [skygragon/leetcode-cli#185]
│Log In... │ERROR:leetcode.auth:Network error: url: https://leetcode.com/api/problems/algorithms/ code: 0
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
                                  │Log In.   │
  File "/Library/Python/2.7/site-packages/terminal_leetcode-0.0.16-py2.7.egg/leetcode/terminal.py", line 193, in run_retrieve_home
    self.leetcode.is_login = auth.is_login()
  File "/Library/Python/2.7/site-packages/terminal_leetcode-0.0.16-py2.7.egg/leetcode/auth.py", line 66, in is_login
    r = retrieve(API_URL, headers=headers)
  File "/Library/Python/2.7/site-packages/terminal_leetcode-0.0.16-py2.7.egg/leetcode/auth.py", line 82, in retrieve
    raise NetworkError('Network error: url: %s' % url)
NetworkError

**Comment by echo-xiao** [comment]
when I try 
'''
leetcode
'''
It throws the network error.
