### ISSUE TITLE
Failed to Retrieve User Favorites

### ISSUE THREAD

**Issue by Austin-Ma** [skygragon/leetcode-cli#208]
Cannot connect through login

### How to reproduce
leetcode plugin -i cookie.chrome
leetcode user -l

### Stack Trace below
[WARN] Failed to retrieve user favorites: [object Object]
/usr/local/lib/node_modules/leetcode-cli/lib/plugins/leetcode.js:515
        user.paid = _user.isCurrentUserPremium;
                          ^

TypeError: Cannot read property 'isCurrentUserPremium' of null
    at /usr/local/lib/node_modules/leetcode-cli/lib/plugins/leetcode.js:515:27
    at Request._callback (/usr/local/lib/node_modules/leetcode-cli/lib/plugins/leetcode.js:421:12)
    at Request.self.callback (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/leetcode-cli/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (eve

### Environment
leetcode-cli version: 2.6.2
OS version: 10.15.3
Node Version: 13.12.0
NPM version : 6.14.4

**Comment by sanketvega** [comment]
+1

**Comment by Austin-Ma** [comment]
Resolved with 
https://github.com/skygragon/leetcode-cli/issues/194#issuecomment-559839631
