### ISSUE TITLE
plugin.next.login is not a function

### ISSUE THREAD

**Issue by lushuangning** [skygragon/leetcode-cli#210]
#180 # Problem Summary
After I execute the command “leetcode user -l”, it shows that the login failed and I get the following error message:

```
readline.js:1150
            throw err;
            ^

TypeError: plugin.next.login is not a function
    at Plugin.plugin.login (/usr/lib/node_modules/leetcode-cli/lib/plugins/cache.js:65:15)
    at /usr/lib/node_modules/leetcode-cli/lib/commands/user.js:50:12
    at /usr/lib/node_modules/leetcode-cli/node_modules/_prompt@1.0.0@prompt/lib/prompt.js:336:32
    at /usr/lib/node_modules/leetcode-cli/node_modules/_async@0.9.2@async/lib/async.js:154:25
    at assembler (/usr/lib/node_modules/leetcode-cli/node_modules/_prompt@1.0.0@prompt/lib/prompt.js:333:9)
    at /usr/lib/node_modules/leetcode-cli/node_modules/_prompt@1.0.0@prompt/lib/prompt.js:342:32
    at /usr/lib/node_modules/leetcode-cli/node_modules/_prompt@1.0.0@prompt/lib/prompt.js:625:5
    at Interface.onLine (/usr/lib/node_modules/leetcode-cli/node_modules/_read@1.0.7@read/lib/read.js:111:5)
    at Interface.emit (events.js:315:20)
    at Interface._onLine (readline.js:337:10)
```

How can I do to solve this problem?

### Environment
```
 _           _                  _      
| |         | |                | |     
| | ___  ___| |_  ___  ___   __| | ___ 
| |/ _ \/ _ \ __|/ __|/ _ \ / _` |/ _ \
| |  __/  __/ |_  (__| (_) | (_| |  __/
|_|\___|\___|\__|\___|\___/ \__,_|\___|  CLI v2.6.2

[Environment]
Node                 v13.14.0
OS                   linux 5.4.0-33-generic
Cache                /home/lushuangning/.lc/leetcode.cn/cache
Config               /home/lushuangning/.lc/config.json

[Configuration]
autologin            {"enable":false,"retry":2}
code                 {"editor":"vim","lang":"cpp"}
file                 {"show":"${fid}.${slug}","submission":"${fid}.${slug}.${sid}.${ac}"}
color                {"enable":true,"theme":"default"}
icon                 {"theme":""}
network              {"concurrency":10,"delay":1}
app                  "leetcode.cn"

[Themes]
Colors               blue,dark,default,molokai,orange,pink,solarized,solarized.light
Icons                ascii,default,win7

[Plugins]
solution.discuss     2019.02.03
company              2017.12.18
cpp.lint             2017.07.27
cpp.run              2017.07.29
github               2018.11.18
cache                default
retry                default
leetcode.cn          2018.11.25
lintcode             2018.11.18
cookie.chrome        2018.11.18
cookie.firefox       2018.11.19
leetcode             default
```

**Comment by gucoi** [comment]
mark，do you have sovle the problem.
