### ISSUE TITLE
login with error: [ERROR] Error: certificate has expired

### ISSUE THREAD

**Issue by zxmrlc** [skygragon/leetcode-cli#213]
first  I replace all leetcode.com with leetcode-cn.com in /usr/local/lib/node_modules/leetcode-cli
then login .
root@NC:~# leetcode user -l -vv
[TRACE] initializing all plugins
[TRACE] found plugin: cache=default
[TRACE] found plugin: leetcode=default
[TRACE] found plugin: retry=default
[TRACE] inited plugin: leetcode
[TRACE] inited plugin: retry
[TRACE] inited plugin: cache
login: myAccount
pass: 
[DEBUG] running leetcode.login
[DEBUG] running leetcode.signin
⠋ Signing in leetcode-cn.com[TRACE] REQUEST %s { uri: 'https://leetcode-cn.com/accounts/login/',
  callback: [Function] }
[TRACE] REQUEST %s make request https://leetcode-cn.com/accounts/login/
`[ERROR] Error: certificate has expired`

**Comment by DeJoker** [comment]
+1 我的情况是

[ERROR] Error: certificate has expired
login: pass: /root/.vscode-server/extensions/leetcode.vscode-leetcode-0.16.2/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:565
    const redirectUri = resp.request.uri.href;

TypeError: Cannot read property 'request' of undefined
    at Request._callback (/root/.vscode-server/extensions/leetcode.vscode-leetcode-0.16.2/node_modules/vsc-leetcode-cli/lib/plugins/leetcode.js:565:30)
    at self.callback (/root/.vscode-server/extensions/leetcode.vscode-leetcode-0.16.2/node_modules/request/request.js:185:22)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestError (/root/.vscode-server/extensions/leetcode.vscode-leetcode-0.16.2/node_modules/request/request.js:881:8)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
