### ISSUE TITLE
Error: spawn vim ENOENT

### ISSUE THREAD

**Issue by hdchen-17media** [skygragon/leetcode-cli#88]
### Problem Summary

When I execute the command from docker installed leetcode-cli, it failed and thrown the exception.

### How to reproduce
leetcode show 780 -ge -l java

events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: spawn vim ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:389:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
    at Function.Module.runMain (module.js:703:11)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3

### Environment
- OS version: Mac OS X

**Comment by skygragon** [comment]
docker container is running in an isolated env that can't access outer host files (e.g. vim binary in your case) unless mounted explicitly. I would expect to only use docker leetcode-cli as a taste since it doesn't support all features like external editor.
